// DESAFIO: 
// CRIE UM SISTEMA DE CALCULO DE NOTAS PARA UMA ESCOLA
// DEVE TER AS SEGUINTES FUNCIONALIDADES:
// - ADICIONAR E REMOVER NOTAS
// - CALCULAR MÉDIA
// - VERIFICAR SE O ALUNO FOI APROVADO, REPROVADO OU ESTÁ DE RECUPERAÇÃO

// REGRAS:
// - A MÉDIA PARA APROVAÇÃO É 7
// - A MÉDIA PARA RECUPERAÇÃO É ENTRE 5 E 7
// - A MÉDIA PARA REPROVAÇÃO É MENOR QUE 5
