// DESAFIO: 
// CRIE UM SISTEMA DE CALCULO DE NOTAS PARA UMA ESCOLA
// DEVE RECEBER UMA LISTA COM AS NOTAS DO ALUNO
// CRIE UMA VARIAVEL PARA ARMAZENAR A MÉDIA DO ALUNO
// PERCORRAR PELA LISTA PARA CALCULAR A MÉDIA DO ALUNO
// PEGUE A MEDIA E VERIFIQUE SE O ALUNO FOI APROVADO, REPROVADO OU ESTÁ DE RECUPERAÇÃO E IMPRIMA O RESULTADO NO CONSOLE
// A MÉDIA PARA APROVAÇÃO É 7, PARA RECUPERAÇÃO É ENTRE 5 E 7, E PARA REPROVAÇÃO É MENOR QUE 5